// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SavedVenue struct {
	ID      int64              `json:"id"`
	SquadID string             `json:"squad_id"`
	UserID  string             `json:"user_id"`
	PlaceID string             `json:"place_id"`
	Name    string             `json:"name"`
	SavedAt pgtype.Timestamptz `json:"saved_at"`
}

type VenueVisit struct {
	ID              int64              `json:"id"`
	SquadID         string             `json:"squad_id"`
	EventID         string             `json:"event_id"`
	PlaceID         string             `json:"place_id"`
	Name            string             `json:"name"`
	VisitedAt       pgtype.Timestamptz `json:"visited_at"`
	AvgSpendInPaise pgtype.Int8        `json:"avg_spend_in_paise"`
}
