// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	GetVisitHistory(ctx context.Context, squadID string) ([]GetVisitHistoryRow, error)
	IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error)
	ListFavorites(ctx context.Context, squadID string) ([]SavedVenue, error)
	RecordVisit(ctx context.Context, arg RecordVisitParams) error
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
}

var _ Querier = (*Queries)(nil)
