// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_venues.sql

package db

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO saved_venues (squad_id, user_id, place_id, name)
VALUES ($1, $2, $3, $4)
`

type AddFavoriteParams struct {
	SquadID string `json:"squad_id"`
	UserID  string `json:"user_id"`
	PlaceID string `json:"place_id"`
	Name    string `json:"name"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite,
		arg.SquadID,
		arg.UserID,
		arg.PlaceID,
		arg.Name,
	)
	return err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS (SELECT 1
               FROM saved_venues
               WHERE squad_id = $1
                 AND user_id = $2
                 AND place_id = $3) AS exists
`

type IsFavoriteParams struct {
	SquadID string `json:"squad_id"`
	UserID  string `json:"user_id"`
	PlaceID string `json:"place_id"`
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.SquadID, arg.UserID, arg.PlaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavorites = `-- name: ListFavorites :many
SELECT id, squad_id, user_id, place_id, name, saved_at
FROM saved_venues
WHERE squad_id = $1
ORDER BY saved_at DESC
`

func (q *Queries) ListFavorites(ctx context.Context, squadID string) ([]SavedVenue, error) {
	rows, err := q.db.Query(ctx, listFavorites, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedVenue
	for rows.Next() {
		var i SavedVenue
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.UserID,
			&i.PlaceID,
			&i.Name,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE
FROM saved_venues
WHERE squad_id = $1
  AND user_id = $2
  AND place_id = $3
`

type RemoveFavoriteParams struct {
	SquadID string `json:"squad_id"`
	UserID  string `json:"user_id"`
	PlaceID string `json:"place_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.SquadID, arg.UserID, arg.PlaceID)
	return err
}
