// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venue_visits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVisitHistory = `-- name: GetVisitHistory :many
SELECT place_id, name, COUNT(*) AS visit_count, MAX(visited_at) AS last_visited_at
FROM venue_visits
WHERE squad_id = $1
GROUP BY place_id, name
ORDER BY last_visited_at DESC
`

type GetVisitHistoryRow struct {
	PlaceID       string      `json:"place_id"`
	Name          string      `json:"name"`
	VisitCount    int64       `json:"visit_count"`
	LastVisitedAt interface{} `json:"last_visited_at"`
}

func (q *Queries) GetVisitHistory(ctx context.Context, squadID string) ([]GetVisitHistoryRow, error) {
	rows, err := q.db.Query(ctx, getVisitHistory, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVisitHistoryRow
	for rows.Next() {
		var i GetVisitHistoryRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.Name,
			&i.VisitCount,
			&i.LastVisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVisit = `-- name: RecordVisit :exec
INSERT INTO venue_visits (squad_id, event_id, place_id, name, visited_at, avg_spend_in_paise)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordVisitParams struct {
	SquadID         string             `json:"squad_id"`
	EventID         string             `json:"event_id"`
	PlaceID         string             `json:"place_id"`
	Name            string             `json:"name"`
	VisitedAt       pgtype.Timestamptz `json:"visited_at"`
	AvgSpendInPaise pgtype.Int8        `json:"avg_spend_in_paise"`
}

func (q *Queries) RecordVisit(ctx context.Context, arg RecordVisitParams) error {
	_, err := q.db.Exec(ctx, recordVisit,
		arg.SquadID,
		arg.EventID,
		arg.PlaceID,
		arg.Name,
		arg.VisitedAt,
		arg.AvgSpendInPaise,
	)
	return err
}
